//write a prog
#include<stdio.h>
#include<math.h>

int main(){
    int p, g ;
    int xa, xb, k1, k2, ya, yb ;
     
     printf("Enter the value of p and g such that they should be primitive roots\n");
     
     printf("Enter the value of p:");
     scanf("%d",&p);

     printf("Enter the value of g:");
     scanf("%d",&g);

     printf ("Enter the selected private key by alice:");
     scanf("%d",&xa);
    
     printf ("Enter the selected public key by bob:");
     scanf("%d",&xb);

     ya=(int)pow(g,xa)%p;
     printf("The secret key for alice is :%d \n",ya);
     yb=(int)pow(g,xb)%p;
     printf("The secret key for bob is :%d\n",yb);
     k1=(int)pow(yb,xa)%p;
     printf("The key generated by alice is :%d\n",k1);
     k2=(int)pow(ya,xb)%p;
     printf("The key generated by bob is :%d\n",k2);

     if (k1==k2){
        printf("Key generated by both alice and bob is similar. So, the key is exchanged ");
     }
     else{
     printf("Key generated by both alice and bob is not similar. So, the key is not exchanged ");

     }

    
}